import React from "react"
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer"
import type { Scan, ScanFlag } from "./types"

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica" },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 20, borderBottom: 1, borderColor: "#e2e8f0", paddingBottom: 10 },
  title: { fontSize: 18, fontWeight: "bold" },
  subtitle: { fontSize: 10, color: "#64748b" },
  scoreSection: { alignItems: "center", marginBottom: 20 },
  scoreNumber: { fontSize: 48, fontWeight: "bold" },
  scoreLabel: { fontSize: 12, color: "#64748b", marginTop: 4 },
  sectionTitle: { fontSize: 14, fontWeight: "bold", marginTop: 16, marginBottom: 8 },
  originalText: { backgroundColor: "#f8fafc", padding: 12, borderRadius: 4, lineHeight: 1.5 },
  flagRow: { flexDirection: "row", borderBottom: 1, borderColor: "#e2e8f0", paddingVertical: 6 },
  flagCell: { flex: 1, paddingHorizontal: 4 },
  flagHeader: { fontWeight: "bold", backgroundColor: "#f1f5f9", paddingVertical: 4, paddingHorizontal: 4 },
  rewriteBox: { backgroundColor: "#f0fdf4", padding: 12, borderRadius: 4, lineHeight: 1.5 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center", fontSize: 8, color: "#94a3b8" },
  riskHigh: { color: "#dc2626" },
  riskMedium: { color: "#d97706" },
  riskLow: { color: "#2563eb" },
})

export function ScanPdfDocument({ scan, clinicName }: { scan: Scan; clinicName: string }) {
  const flags = (scan.flags || []) as ScanFlag[]
  const riskStyle = (level: string) =>
    level === "high" ? styles.riskHigh : level === "medium" ? styles.riskMedium : styles.riskLow

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.title}>RegenCompliance</Text>
            <Text style={styles.subtitle}>{clinicName}</Text>
          </View>
          <View>
            <Text style={styles.subtitle}>Compliance Scan Report</Text>
            <Text style={styles.subtitle}>{new Date(scan.created_at).toLocaleDateString()}</Text>
          </View>
        </View>

        <View style={styles.scoreSection}>
          <Text style={styles.scoreNumber}>{scan.compliance_score ?? "N/A"}</Text>
          <Text style={styles.scoreLabel}>Compliance Score</Text>
        </View>

        <Text style={styles.sectionTitle}>Original Content</Text>
        <View style={styles.originalText}>
          <Text>{scan.original_text}</Text>
        </View>

        {flags.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Flagged Phrases ({flags.length})</Text>
            <View style={[styles.flagRow, { borderBottom: 0 }]}>
              <Text style={[styles.flagCell, styles.flagHeader]}>Phrase</Text>
              <Text style={[styles.flagCell, styles.flagHeader]}>Risk</Text>
              <Text style={[styles.flagCell, styles.flagHeader]}>Reason</Text>
              <Text style={[styles.flagCell, styles.flagHeader]}>Alternative</Text>
            </View>
            {flags.map((flag, i) => (
              <View key={i} style={styles.flagRow} wrap={false}>
                <Text style={styles.flagCell}>{flag.matched_text}</Text>
                <Text style={[styles.flagCell, riskStyle(flag.risk_level)]}>{flag.risk_level.toUpperCase()}</Text>
                <Text style={styles.flagCell}>{flag.reason}</Text>
                <Text style={styles.flagCell}>{flag.alternative}</Text>
              </View>
            ))}
          </>
        )}

        {scan.rewritten_text && (
          <>
            <Text style={styles.sectionTitle}>Compliant Rewrite</Text>
            <View style={styles.rewriteBox}>
              <Text>{scan.rewritten_text}</Text>
            </View>
          </>
        )}

        <Text style={styles.footer}>
          Generated by RegenCompliance. Educational purposes only. Not legal advice.
        </Text>
      </Page>
    </Document>
  )
}
