-- Seed: 30 real FDA/FTC-flagged phrases for regenerative medicine
INSERT INTO compliance_rules (banned_phrase, banned_phrase_variants, compliant_alternative, risk_level, applies_to, category, source_url, source_name, source_date) VALUES

-- HIGH RISK — Direct cure/treatment claims
('cures',
 ARRAY['cure', 'cured', 'curing', 'can cure'],
 'Many patients report significant improvement in symptoms',
 'high', ARRAY['stem_cell', 'prp', 'exosomes', 'bmac', 'whartons_jelly', 'prolotherapy', 'peptide'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-06-15'),

('heals',
 ARRAY['heal', 'healed', 'healing power', 'complete healing'],
 'May support the body''s natural healing processes',
 'high', ARRAY['stem_cell', 'prp', 'exosomes', 'bmac', 'whartons_jelly', 'prolotherapy'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-06-15'),

('treats',
 ARRAY['treat', 'treated', 'treating', 'treatment for'],
 'Patients seek this procedure to address concerns related to',
 'high', ARRAY['stem_cell', 'prp', 'exosomes', 'bmac', 'whartons_jelly'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-03-22'),

('reverses',
 ARRAY['reverse', 'reversed', 'reversing', 'reversal of'],
 'Some patients experience noticeable improvement in their condition',
 'high', ARRAY['stem_cell', 'exosomes', 'peptide'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-05-10'),

('FDA-approved stem cells',
 ARRAY['FDA approved stem cell', 'FDA-cleared stem cells', 'FDA approved therapy'],
 'Performed in an FDA-registered facility using established protocols',
 'high', ARRAY['stem_cell', 'bmac', 'whartons_jelly'],
 'fda_approval',
 'https://www.fda.gov/vaccines-blood-biologics/cellular-gene-therapy-products/approved-cellular-and-gene-therapy-products',
 'FDA CBER', '2024-01-15'),

('eliminates',
 ARRAY['eliminate', 'eliminated', 'eliminating', 'elimination of'],
 'Many patients report a reduction in symptoms',
 'high', ARRAY['stem_cell', 'prp', 'exosomes', 'bmac', 'prolotherapy'],
 'health_claims',
 'https://www.ftc.gov/news-events/news/press-releases',
 'FTC Press Release', '2024-04-18'),

('repairs damage',
 ARRAY['repair damage', 'repairs damaged', 'tissue repair guaranteed'],
 'May support tissue recovery and regeneration processes',
 'high', ARRAY['stem_cell', 'prp', 'exosomes', 'bmac'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-07-02'),

('regrows',
 ARRAY['regrow', 'regrowth', 'regrowing', 'grow back'],
 'Some patients report improvements in tissue quality over time',
 'high', ARRAY['stem_cell', 'prp', 'exosomes'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-02-28'),

('proven to',
 ARRAY['has been proven', 'is proven', 'scientifically proven', 'clinically proven'],
 'Research suggests potential benefits; individual results may vary',
 'high', ARRAY['stem_cell', 'prp', 'exosomes', 'bmac', 'whartons_jelly', 'prolotherapy', 'peptide'],
 'efficacy',
 'https://www.ftc.gov/news-events/news/press-releases',
 'FTC Press Release', '2024-05-20'),

('guaranteed results',
 ARRAY['guarantee results', 'results guaranteed', 'we guarantee', '100% effective'],
 'Individual results may vary; outcomes depend on multiple factors',
 'high', ARRAY['stem_cell', 'prp', 'exosomes', 'bmac', 'whartons_jelly', 'prolotherapy', 'peptide'],
 'efficacy',
 'https://www.ftc.gov/news-events/news/press-releases',
 'FTC Press Release', '2024-06-30'),

('scientifically proven cure',
 ARRAY['scientific cure', 'proven cure', 'proven treatment'],
 'Emerging research shows promising results; individual outcomes vary',
 'high', ARRAY['stem_cell', 'prp', 'exosomes', 'bmac'],
 'efficacy',
 'https://www.ftc.gov/news-events/news/press-releases',
 'FTC Press Release', '2024-03-15'),

('restores function completely',
 ARRAY['complete restoration', 'fully restores', 'total recovery'],
 'Many patients report improved function and mobility',
 'high', ARRAY['stem_cell', 'prp', 'bmac', 'prolotherapy'],
 'efficacy',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-08-05'),

('no side effects',
 ARRAY['zero side effects', 'side effect free', 'completely safe', 'risk-free'],
 'Side effects are generally minimal; your provider will discuss potential risks',
 'high', ARRAY['stem_cell', 'prp', 'exosomes', 'bmac', 'whartons_jelly', 'prolotherapy', 'peptide'],
 'safety',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-04-12'),

('safe for everyone',
 ARRAY['safe for all', 'universally safe', 'anyone can benefit'],
 'Candidacy is determined on an individual basis during consultation',
 'high', ARRAY['stem_cell', 'prp', 'exosomes', 'bmac', 'whartons_jelly', 'prolotherapy', 'peptide'],
 'safety',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-05-28'),

('miracle treatment',
 ARRAY['miracle cure', 'miraculous results', 'miracle therapy'],
 'An innovative approach that many patients find beneficial',
 'high', ARRAY['stem_cell', 'prp', 'exosomes', 'bmac', 'whartons_jelly'],
 'health_claims',
 'https://www.ftc.gov/news-events/news/press-releases',
 'FTC Press Release', '2024-07-14'),

('breakthrough cure',
 ARRAY['breakthrough treatment', 'revolutionary cure', 'groundbreaking cure'],
 'An advanced procedure supported by growing clinical interest',
 'high', ARRAY['stem_cell', 'exosomes', 'bmac'],
 'health_claims',
 'https://www.ftc.gov/news-events/news/press-releases',
 'FTC Press Release', '2024-02-10'),

('eradicates',
 ARRAY['eradicate', 'eradicated', 'eradicating'],
 'Patients may experience significant symptom relief',
 'high', ARRAY['stem_cell', 'prp', 'exosomes'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-06-22'),

('destroys disease',
 ARRAY['destroy disease', 'kills disease', 'fights disease'],
 'Supports the body''s response to underlying conditions',
 'high', ARRAY['stem_cell', 'exosomes', 'peptide'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-08-18'),

('permanent solution',
 ARRAY['permanent fix', 'permanent cure', 'once and for all'],
 'Results vary by individual; some patients report long-lasting benefits',
 'high', ARRAY['stem_cell', 'prp', 'exosomes', 'bmac', 'whartons_jelly', 'prolotherapy'],
 'efficacy',
 'https://www.ftc.gov/news-events/news/press-releases',
 'FTC Press Release', '2024-03-30'),

('replaces surgery',
 ARRAY['replace surgery', 'avoid surgery', 'instead of surgery', 'alternative to surgery'],
 'Some patients explore this option before considering surgical intervention',
 'high', ARRAY['stem_cell', 'prp', 'bmac', 'prolotherapy'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-04-25'),

('regenerates organs',
 ARRAY['organ regeneration', 'regenerate organs', 'regrow organs'],
 'Research is exploring the potential role of regenerative therapies in tissue support',
 'high', ARRAY['stem_cell', 'exosomes'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-09-01'),

('reverses aging completely',
 ARRAY['reverse aging', 'anti-aging cure', 'turn back the clock'],
 'Patients report feeling more youthful and energetic after treatment',
 'high', ARRAY['stem_cell', 'exosomes', 'peptide'],
 'health_claims',
 'https://www.ftc.gov/news-events/news/press-releases',
 'FTC Press Release', '2024-05-05'),

('treats cancer',
 ARRAY['treat cancer', 'cancer treatment', 'cancer cure', 'fights cancer'],
 'This therapy is not intended to diagnose, treat, cure, or prevent cancer',
 'high', ARRAY['stem_cell', 'exosomes'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-07-28'),

('cures Alzheimers',
 ARRAY['cure Alzheimer''s', 'Alzheimer''s treatment', 'treats dementia', 'cures dementia'],
 'This therapy is not indicated for neurological conditions such as Alzheimer''s disease',
 'high', ARRAY['stem_cell', 'exosomes'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-06-08'),

('fixes nerve damage permanently',
 ARRAY['fix nerve damage', 'permanent nerve repair', 'nerve regeneration guaranteed'],
 'Some patients report improvements in nerve-related symptoms over time',
 'high', ARRAY['stem_cell', 'exosomes', 'peptide'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-08-12'),

-- MEDIUM RISK — Overstated efficacy
('removes arthritis',
 ARRAY['remove arthritis', 'eliminates arthritis', 'arthritis cure'],
 'Some patients report reduced joint discomfort and improved mobility',
 'medium', ARRAY['stem_cell', 'prp', 'bmac', 'prolotherapy'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-03-05'),

('eliminates chronic pain forever',
 ARRAY['permanent pain relief', 'pain-free forever', 'end chronic pain'],
 'Many patients experience meaningful pain relief; duration of benefits varies',
 'medium', ARRAY['stem_cell', 'prp', 'bmac', 'prolotherapy', 'peptide'],
 'health_claims',
 'https://www.ftc.gov/news-events/news/press-releases',
 'FTC Press Release', '2024-04-02'),

('repairs spinal damage',
 ARRAY['spinal repair', 'fix spinal cord', 'spinal regeneration'],
 'Some patients with spinal concerns report symptom improvement; results vary',
 'medium', ARRAY['stem_cell', 'exosomes'],
 'health_claims',
 'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters',
 'FDA Warning Letters', '2024-09-15'),

-- LOW RISK — Testimonial/marketing overreach
('FDA cleared therapy',
 ARRAY['FDA cleared', 'FDA approved procedure', 'government approved'],
 'Performed using protocols consistent with FDA guidance for regenerative procedures',
 'low', ARRAY['stem_cell', 'prp', 'exosomes', 'bmac', 'whartons_jelly'],
 'fda_approval',
 'https://www.fda.gov/vaccines-blood-biologics/cellular-gene-therapy-products/approved-cellular-and-gene-therapy-products',
 'FDA CBER', '2024-01-15'),

('clinically proven cure',
 ARRAY['clinically proven', 'clinical proof', 'studies prove'],
 'Supported by emerging clinical research; individual outcomes may vary',
 'low', ARRAY['stem_cell', 'prp', 'exosomes', 'bmac', 'whartons_jelly', 'prolotherapy', 'peptide'],
 'efficacy',
 'https://www.ftc.gov/news-events/news/press-releases',
 'FTC Press Release', '2024-02-20');
